### ISSUE TITLE
What is the proper based platform or dependencies for this?

### ISSUE THREAD

**Issue by iitgrad** [artik-iot/artik-sdk#10]
I am getting the following error when running the following lines on resin.io using the fedora-node platform.

const artik = require('artik-sdk');  // Include dependencies of the Artik SDK.
const name = artik.get_platform_name();

console.log(name);

The error is as follows:
basic-gpio@0.0.1 start /usr/src/app
21.08.16 08:42:09 [-0500] > node app.js
21.08.16 08:42:09 [-0500]
21.08.16 08:42:09 [-0500] module.js:583
21.08.16 08:42:09 [-0500] return process.dlopen(module, path._makeLong(filename));
21.08.16 08:42:09 [-0500] ^
21.08.16 08:42:09 [-0500]
21.08.16 08:42:09 [-0500] Error: libartik-sdk-base.so.0.13: cannot open shared object file: No such file or directory
21.08.16 08:42:09 [-0500] at Error (native)
21.08.16 08:42:09 [-0500] at Object.Module._extensions..node (module.js:583:18)
21.08.16 08:42:09 [-0500] at Module.load (module.js:473:32)
21.08.16 08:42:09 [-0500] at tryModuleLoad (module.js:432:12)
21.08.16 08:42:09 [-0500] at Function.Module._load (module.js:424:3)
21.08.16 08:42:09 [-0500] at Module.require (module.js:483:17)
21.08.16 08:42:09 [-0500] at require (internal/module.js:20:19)
21.08.16 08:42:09 [-0500] at Object.<anonymous> (/usr/src/app/node_modules/artik-sdk/src/index.js:6:13)
21.08.16 08:42:09 [-0500] at Module._compile (module.js:556:32)
21.08.16 08:42:09 [-0500] at Object.Module._extensions..js (module.js:565:10)

**Comment by artik-iot** [comment]
Hi Kevin,

You need to have the Artik SDK libraries installed to have the node.js layer work.

If you properly installed our public repo, then you should be able to install those by doing:

$ dnf install libartik-sdk-tests

This will only work on Fedora 22/24 images.

________________________________
From: Kevin McQuown
Sent: Sunday, August 21, 2016 4:18:27 PM
To: artik-iot/artik-sdk
Subject: [artik-iot/artik-sdk] What is the proper based platform or dependencies for this? (#10)


I am getting the following error when running the following lines on resin.io using the fedora-node platform.

const artik = require('artik-sdk'); // Include dependencies of the Artik SDK.
const name = artik.get_platform_name();

console.log(name);

The error is as follows:
basic-gpio@0.0.1 start /usr/src/app
21.08.16 08:42:09 [-0500] > node app.js
21.08.16 08:42:09 [-0500]
21.08.16 08:42:09 [-0500] module.js:583
21.08.16 08:42:09 [-0500] return process.dlopen(module, path._makeLong(filename));
21.08.16 08:42:09 [-0500] ^
21.08.16 08:42:09 [-0500]
21.08.16 08:42:09 [-0500] Error: libartik-sdk-base.so.0.13: cannot open shared object file: No such file or directory
21.08.16 08:42:09 [-0500] at Error (native)
21.08.16 08:42:09 [-0500] at Object.Module._extensions..node (module.js:583:18)
21.08.16 08:42:09 [-0500] at Module.load (module.js:473:32)
21.08.16 08:42:09 [-0500] at tryModuleLoad (module.js:432:12)
21.08.16 08:42:09 [-0500] at Function.Module._load (module.js:424:3)
21.08.16 08:42:09 [-0500] at Module.require (module.js:483:17)
21.08.16 08:42:09 [-0500] at require (internal/module.js:20:19)
21.08.16 08:42:09 [-0500] at Object. (/usr/src/app/node_modules/artik-sdk/src/index.js:6:13)
21.08.16 08:42:09 [-0500] at Module._compile (module.js:556:32)
21.08.16 08:42:09 [-0500] at Object.Module._extensions..js (module.js:565:10)

�

**Comment by iitgrad** [comment]
Awesome, I'm running Fedora 24 but the install fails saying that it cannot find libartik-sdk-tests

**Comment by glemercier** [comment]
Hi Kevin,

The Artik SDK is not publicly released yet but should be within next few weeks. Stay tuned on artik.io for upcoming announcements.

Thanks for your interest.
